package cl.aiep.carrito.dao;
// Generated 15-08-2017 3:26:33 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto implements java.io.Serializable
{

	private Long id;
	private Categoria categoria;
	private String nombre;
	private String descripcion;
	private double valor;
	private Integer stock;
	private int idcategoria;
	private Set pedidoProductos = new HashSet(0);

	public Producto()
	{
	}

	public Producto(Categoria categoria, String nombre, String descripcion, double valor, int idcategoria)
	{
		this.categoria = categoria;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.valor = valor;
		this.idcategoria = idcategoria;
	}

	public Producto(Categoria categoria, String nombre, String descripcion, double valor, Integer stock,
			int idcategoria, Set pedidoProductos)
	{
		this.categoria = categoria;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.valor = valor;
		this.stock = stock;
		this.idcategoria = idcategoria;
		this.pedidoProductos = pedidoProductos;
	}

	public Long getId()
	{
		return this.id;
	}

	public void setId(Long id)
	{
		this.id = id;
	}

	public Categoria getCategoria()
	{
		return this.categoria;
	}

	public void setCategoria(Categoria categoria)
	{
		this.categoria = categoria;
	}

	public String getNombre()
	{
		return this.nombre;
	}

	public void setNombre(String nombre)
	{
		this.nombre = nombre;
	}

	public String getDescripcion()
	{
		return this.descripcion;
	}

	public void setDescripcion(String descripcion)
	{
		this.descripcion = descripcion;
	}

	public double getValor()
	{
		return this.valor;
	}

	public void setValor(double valor)
	{
		this.valor = valor;
	}

	public Integer getStock()
	{
		return this.stock;
	}

	public void setStock(Integer stock)
	{
		this.stock = stock;
	}

	public int getIdcategoria()
	{
		return this.idcategoria;
	}

	public void setIdcategoria(int idcategoria)
	{
		this.idcategoria = idcategoria;
	}

	public Set getPedidoProductos()
	{
		return this.pedidoProductos;
	}

	public void setPedidoProductos(Set pedidoProductos)
	{
		this.pedidoProductos = pedidoProductos;
	}

}
