package cl.aiep.carrito.dao;
// Generated 15-08-2017 3:28:25 by Hibernate Tools 5.2.3.Final

/**
 * Categoria generated by hbm2java
 */
public class Categoria implements java.io.Serializable
{

	private Long id;
	private String nombre;
	private Producto producto;

	public Categoria()
	{
	}

	public Categoria(String nombre)
	{
		this.nombre = nombre;
	}

	public Categoria(String nombre, Producto producto)
	{
		this.nombre = nombre;
		this.producto = producto;
	}

	public Long getId()
	{
		return this.id;
	}

	public void setId(Long id)
	{
		this.id = id;
	}

	public String getNombre()
	{
		return this.nombre;
	}

	public void setNombre(String nombre)
	{
		this.nombre = nombre;
	}

	public Producto getProducto()
	{
		return this.producto;
	}

	public void setProducto(Producto producto)
	{
		this.producto = producto;
	}

}
