package cl.aiep.carrito.dao;
// Generated 15-08-2017 3:28:25 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * EstadoProducto generated by hbm2java
 */
public class EstadoProducto implements java.io.Serializable
{

	private Long id;
	private String nombre;
	private Set pedidoProductos = new HashSet(0);

	public EstadoProducto()
	{
	}

	public EstadoProducto(String nombre)
	{
		this.nombre = nombre;
	}

	public EstadoProducto(String nombre, Set pedidoProductos)
	{
		this.nombre = nombre;
		this.pedidoProductos = pedidoProductos;
	}

	public Long getId()
	{
		return this.id;
	}

	public void setId(Long id)
	{
		this.id = id;
	}

	public String getNombre()
	{
		return this.nombre;
	}

	public void setNombre(String nombre)
	{
		this.nombre = nombre;
	}

	public Set getPedidoProductos()
	{
		return this.pedidoProductos;
	}

	public void setPedidoProductos(Set pedidoProductos)
	{
		this.pedidoProductos = pedidoProductos;
	}

}
