package cl.aiep.carrito.dao;
// Generated 15-08-2017 3:28:25 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable
{

	private Long id;
	private String nombre;
	private String apellido1;
	private String apellido2;
	private int rut;
	private String direccion;
	private String mail;
	private Integer telefono;
	private String user;
	private String password;
	private Set pedidoProductos = new HashSet(0);

	public Usuario()
	{
	}

	public Usuario(String nombre, String apellido1, String apellido2, int rut, String direccion, String mail,
			String user, String password)
	{
		this.nombre = nombre;
		this.apellido1 = apellido1;
		this.apellido2 = apellido2;
		this.rut = rut;
		this.direccion = direccion;
		this.mail = mail;
		this.user = user;
		this.password = password;
	}

	public Usuario(String nombre, String apellido1, String apellido2, int rut, String direccion, String mail,
			Integer telefono, String user, String password, Set pedidoProductos)
	{
		this.nombre = nombre;
		this.apellido1 = apellido1;
		this.apellido2 = apellido2;
		this.rut = rut;
		this.direccion = direccion;
		this.mail = mail;
		this.telefono = telefono;
		this.user = user;
		this.password = password;
		this.pedidoProductos = pedidoProductos;
	}

	public Long getId()
	{
		return this.id;
	}

	public void setId(Long id)
	{
		this.id = id;
	}

	public String getNombre()
	{
		return this.nombre;
	}

	public void setNombre(String nombre)
	{
		this.nombre = nombre;
	}

	public String getApellido1()
	{
		return this.apellido1;
	}

	public void setApellido1(String apellido1)
	{
		this.apellido1 = apellido1;
	}

	public String getApellido2()
	{
		return this.apellido2;
	}

	public void setApellido2(String apellido2)
	{
		this.apellido2 = apellido2;
	}

	public int getRut()
	{
		return this.rut;
	}

	public void setRut(int rut)
	{
		this.rut = rut;
	}

	public String getDireccion()
	{
		return this.direccion;
	}

	public void setDireccion(String direccion)
	{
		this.direccion = direccion;
	}

	public String getMail()
	{
		return this.mail;
	}

	public void setMail(String mail)
	{
		this.mail = mail;
	}

	public Integer getTelefono()
	{
		return this.telefono;
	}

	public void setTelefono(Integer telefono)
	{
		this.telefono = telefono;
	}

	public String getUser()
	{
		return this.user;
	}

	public void setUser(String user)
	{
		this.user = user;
	}

	public String getPassword()
	{
		return this.password;
	}

	public void setPassword(String password)
	{
		this.password = password;
	}

	public Set getPedidoProductos()
	{
		return this.pedidoProductos;
	}

	public void setPedidoProductos(Set pedidoProductos)
	{
		this.pedidoProductos = pedidoProductos;
	}

}
